function [data, auxData, metaData, txtData, weights] = mydata_Squalus_acanthias_br
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Chondrichthyes';
metaData.order      = 'Squaliformes';
metaData.family     = 'Squalidae';
metaData.species    = 'Squalus_acanthias_br';
metaData.species_en = 'no_english_name';

metaData.ecoCode.climate = {'MB','MC'};
metaData.ecoCode.ecozone = {'MAN','MAS','MAm'};
metaData.ecoCode.habitat = {'0iMcd'};
metaData.ecoCode.embryo  = {'Mv'};
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'biCi','biCvf'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(9); % K, body temp

metaData.data_0     = {'ab','tp','am','Lb','Lp','Li','Ww0','Wwp','Wwi','Ri'};
metaData.data_1     = {'LR'};

metaData.COMPLETE   = 2.2; % using criteria of LikaKear2011

metaData.author     = {'Julieta Vigliano'};
metaData.date_subm  = [2023 6 6];
metaData.email      = {'julieta.vigliano@ugent.be'};
metaData.address    = {'Roeispaanstraat 25'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight@tecnico.ulisboa.pt'};
metaData.date_acc   = [2023 6 6];

%% set zero-variate data
data.ab = 690; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'Avsa2001'};
  temp.ab = C2K(9); units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.tp = 2190; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = {'Avsa2001'};
  temp.tp = C2K(9); units.temp.tp = 'K'; label.temp.tp = 'temperature';
data.am = 29200; units.am = 'd'; label.am = 'life span'; bibkey.am = {'Avsa2001'};
  temp.am = C2K(9); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lb = 24; units.Lb = 'cm'; label.Lb = 'length at birth'; bibkey.Lb = {'Avsa2001'};
data.Lp = 72; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = {'Avsa2001'};
data.Li = 136; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'Avsa2001'};

data.Ww0 = 35; units.Ww0 = 'g'; label.Ww0 = 'initial wet weight'; bibkey.Ww0 = {'Avsa2001'};
data.Wwp = 950; units.Wwp = 'g'; label.Wwp = 'wet weight at puberty'; bibkey.Wwp = {'Avsa2001'};
data.Wwi = 9900; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = {'Avsa2001'};

data.Ri = 0.019; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'Avsa2001'};
  temp.Ri = C2K(9); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';

%% set uni-variate data
% length - reproduction rate
data.LR = [ ... 
  72 2.5
  77 2.8
  82 3.2
  87 3.3
  92 4.1
  97 4.7
  102 6.6
  107 7
  112 9
  117 11.4
  122 13.1
  127 14
  132 14
  137 14];
units.LR = {'cm', '#/d'}; label.LR = {'length', 'reproduction rate'};
temp.LR = C2K(9); units.temp.LR = 'K'; label.temp.LR = 'temperature';
bibkey.LR = {'Avsa2001'};

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;

%% Links
metaData.links.id_CoL = ''; % Cat of Life

%% References
bibkey = 'Avsa2001'; type = 'article'; bib = [ ...
'author = {Avsar}, ' ... 
'title = {Age, Growth, Reproduction and Feeding of the Spurdog}, ' ... 
'journal = { southern eastern black sea estuarine coastal and Shelf Science}, ' ... 
'year = {2001}, ' ... 
'volume = {52}, ' ... 
'pages = {269-278}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
